require "sinatra/base"
require "sinatra/cookies"
# require "sinatra/reloader"
require "sinatra/static_assets"
# require "sassc"
require "rack/brotli"
require_relative "controllers"
require_relative "helpers"
